### ISSUE TITLE
Cannot read property 'colors' of undefined

### ISSUE THREAD

**Issue by gustavohellwig** [codeFareith/uebersicht-FancyDateTime#3]
Hi,
Since yesterday it's showing this error: Cannot read property 'colors' of undefined
<img src="http://image.prntscr.com/image/ede8a9bddbff48d48f149cbb2ca0e7f7.png">

Suggestions ?

**Comment by njm2112** [comment]
i'm having the same issue. any ideas?

**Comment by adamdehaven** [comment]
Same here

**Comment by codeFareith** [comment]
Sorry for my late response. Didn't checked github for a while.
Thanks for your bugreport, I'm working on a fix right now, stay tuned :)

**Comment by codeFareith** [comment]
Seems like somebody already fixed it. I'm merging the pull-request

**Comment by gustavohellwig** [comment]
tks, it's working now !!!
