### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by ThomasRiddle** [codeFareith/uebersicht-FancyDateTime#5]
Could you please how to make the box totally transparent? I have tried to modify here but it looks doesn't work.
<img width="1440" alt="screen shot 2017-10-08 at 22 19 17" src="https://user-images.githubusercontent.com/25854424/31324333-316e2ccc-ac77-11e7-8a59-a30b747e85c3.png">

**Comment by ThomasRiddle** [comment]
Sorry to bother you but I do not know how to connect with you.

**Comment by bdpiper** [comment]
I think the change is to background settings in the "Colors" section, set it to 255, 255, 255, **0** and the background becomes transparent

**Comment by codeFareith** [comment]
Sorry for my late response.
To make the box transparent set `background: 'rgba(255, 255, 255, 0)'` in the colors section and `box: '0 0 1.25em rgba(0, 0, 0, 0)'` in the shadows section.
Next: scroll to line 135 and remove the `-webkit-backdrop-filter: blur(10px)`
